apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress

replicaCount: 1
image:
  repository: "wordpress"
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  port: 80
